name: magnetic-anomaly
channels:
    - conda-forge
    - defaults
dependencies:
    - python=2.7
    - numpy
    - scipy
    - pandas
    - jupyter
    - ipython
    - ipywidgets
    - matplotlib
    - basemap
    - fatiando=0.5
